server: 
  port: 9008
spring: 
  application:  
    name: huahua-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.192.129:3306/huahua_user?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.192.129
    port: 6379
  rabbitmq:
    host: 192.168.192.129
    username: admin
    password: 1234
#jwt.config
jwt:
  config:
    key: huahuaCommunity
    #过期时间(一小时)
    ttl: 3600000
#注册到eureka服务中
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
